name: Sync Webflow → GitHub

on:
  workflow_dispatch: # Manual trigger
  schedule:
    - cron: "0 6 * * *" # Runs every day at 6 AM UTC

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install node-fetch

      - name: Run Sync Script
        env:
          WEBFLOW_API_KEY: ${{ secrets.WEBFLOW_API_KEY }}
        run: node pull-webflow.js

      - name: Configure git
        run: |
          git config user.name "webflow-bot"
          git config user.email "webflow-bot@users.noreply.github.com"

      - name: Push changes
        run: |
          git add .
          git commit -m "Auto-sync from Webflow API" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
